### ISSUE TITLE
Duplicate Push Opens Being Logged - Unity iOS

### ISSUE THREAD

**Issue by codyward-skybox** [braze-inc/braze-unity-sdk#84] opened 2021-04-14 16:19 UTC
We are seeing duplicate push opens being logged when the app is opened via a Push Notification.

We send a push notification, open the app once via that notification, and are seeing both a 'Direct Open' and 'Influenced Open' get logged. This is effectively duplicating our push opens. 

This appears to be a race condition, as it does not have 100% reproduction rate. However with the addition of extra external unity packages, which we suspect are causing a slight delay in application launch, the issue is happening more often than not.

It appears the threshold of detecting an 'Influenced Open' is too low.

**Comment by Bucimis** [comment] 2021-04-14 17:11
Hi @codyward-skybox 

Could you provide verbose logs for both the direct+influenced case and the direct only case? You can obtain verbose logs by enabling them in the Braze Config editor and using the Xcode console.

Also, 
1. are you integrating the SDK automatically via the Braze Config editor ("Automate Unity iOS Integration" enabled)?
2. are you integrating push automatically via the Braze Config editor ("Integrate Push With Braze" enabled)?
3. If integrating manually, is your startWithApiKey being called synchronously within your `didFinishLaunchingWithOptions`?

**Comment by codyward-skybox** [comment] 2021-04-14 18:17
Yes we have all the automated integrations enabled, and I can confirm the `startWithApiKey` is being called synchronously within `didFinishLaunchingWithOptions`

I'm having trouble getting logs where a duplicate log _doesnt_ happen. But here are verbose logs for the direct+influenced case.
[duplicate_open_verbose_logs.log](https://github.com/Appboy/appboy-unity-sdk/files/6312879/duplicate_open_verbose_logs.log)

**Comment by Bucimis** [comment] 2021-04-14 19:36
@codyward-skybox thanks for the info! We did some investigation and we think this is due to a timing issue as you mentioned. Your integration seems to be correct, we'll give you a sense of where this fits into our roadmap once we know more and have confirmed the issue.

**Comment by codyward-skybox** [comment] 2021-08-17 00:04
Hello! Some members of my team were looking into this issue again.

I just wondering if there happened to be any updates towards confirming/resolving the timing issue.

**Comment by lowip** [comment] 2021-08-17 17:24
Hi @codyward-skybox,

A similar issue has been resolved in our iOS SDK which has since been released as part of our Unity SDK. We recommend that you upgrade to the latest [release](https://github.com/Appboy/appboy-unity-sdk/releases/).

In the meantime, can you send links to the campaigns on which you noticed the issue to support@braze.com? Please make sure to include a reference to that Github issue as well.

**Comment by hokstuff** [comment] 2023-04-27 21:33
Due to the age of this thread, I am closing it out from inactivity. If you are still experiencing issues, feel free to contact our Support team or open a new thread. Thanks!

**Closed by hokstuff** 2023-04-27 21:33 UTC
